name: Tests 🛠️

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: 🛠️ Tests
        run: go test ./...
